name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # अगर कोई build command हो, ओसे uncomment करें:
      # - name: Build project
      #   run: npm run build  # या कोई custom build step

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: html-css-e-comm

  deploy_production:
    name: Deploy to Production
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: deploy

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}           # आपके सर्वर IP
          username: ${{ secrets.SERVER_USER }}      # जैसे ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}       # SSH private key from secrets
          port: 22
          source: "deploy/html-css-e-comm/**"       # artifact extract folder
          target: "/var/www/html"                   # remote server web root
